name: 'Logs for Netlify'
description: 'Connect the deployment process of Netlify to the GitHub Deployments API.'
author: 'bdougie'
branding:
  icon: 'activity'
  color: 'white'
runs:
  using: 'docker'
  image: 'Dockerfile'
