name: 'Logs for Netlify'
description: 'Connect the deployment process of Netlify to the GitHub Deployments API.'
author: 'Brian Douglas'
branding:
  icon: 'activity'
  color: 'white'
runs:
  using: 'node12'
  main: 'action.js'
